name: lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: build
        run: npm install

      - name: lint-step
        run: make lint